### ISSUE TITLE
v1.6.19 raises "TypeError: Cannot read property 'length' of undefined" error. 

### ISSUE THREAD

**Issue by eflowbeach** [topojson/topojson#246]
I was using the shapefile from here:  http://gis.fema.gov/maps/regions_hqs.zip to make a topojson like this:

```
topojson -o femaregions.json FEMA_Regions.shp

/usr/local/lib/node_modules/topojson/lib/topojson/geomify.js:78
      for (var rings = o.coordinates, i = 0, N = 0, n = rings.length; i < n; +
                                                             ^
TypeError: Cannot read property 'length' of undefined
    at Object.geomifyGeometryType.Polygon (/usr/local/lib/node_modules/topojson/lib/topojson/geomify.js:78:62)
    at geomifyGeometry (/usr/local/lib/node_modules/topojson/lib/topojson/geomify.js:27:94)
    at geomifyFeature (/usr/local/lib/node_modules/topojson/lib/topojson/geomify.js:16:7)
    at Array.forEach (native)
    at geomifyObjectType.FeatureCollection (/usr/local/lib/node_modules/topojson/lib/topojson/geomify.js:36:27)
    at geomifyObject (/usr/local/lib/node_modules/topojson/lib/topojson/geomify.js:8:27)
    at module.exports (/usr/local/lib/node_modules/topojson/lib/topojson/geomify.js:113:20)
    at Object.module.exports [as topology] (/usr/local/lib/node_modules/topojson/lib/topojson/topology.js:45:3)
    at output (/usr/local/lib/node_modules/topojson/bin/topojson:284:25)
    at notify (/usr/local/lib/node_modules/topojson/node_modules/queue-async/queue.js:47:18)
```

**Comment by eflowbeach** [comment]
I forgot to mention that this is very similar to issue #137

**Comment by eflowbeach** [comment]
Still happens...

└── topojson@1.6.27 

eflowbeach:~/workspace/temp $ topojson -o femaregions.json FEMA_Regions.shp
/home/ubuntu/workspace/node_modules/topojson/lib/topojson/geomify.js:78
      for (var rings = o.coordinates, i = 0, N = 0, n = rings.length; i < n; ++i) {
                                                             ^

TypeError: Cannot read property 'length' of undefined
    at Object.geomifyGeometryType.Polygon (/home/ubuntu/workspace/node_modules/topojson/lib/topojson/geomify.js:78:62)
    at geomifyGeometry (/home/ubuntu/workspace/node_modules/topojson/lib/topojson/geomify.js:27:94)
    at geomifyFeature (/home/ubuntu/workspace/node_modules/topojson/lib/topojson/geomify.js:16:7)
    at Array.forEach (native)
    at geomifyObjectType.FeatureCollection (/home/ubuntu/workspace/node_modules/topojson/lib/topojson/geomify.js:36:27)
    at geomifyObject (/home/ubuntu/workspace/node_modules/topojson/lib/topojson/geomify.js:8:27)
    at module.exports (/home/ubuntu/workspace/node_modules/topojson/lib/topojson/geomify.js:113:20)
    at Object.module.exports [as topology] (/home/ubuntu/workspace/node_modules/topojson/lib/topojson/topology.js:45:3)
    at output (/home/ubuntu/workspace/node_modules/topojson/bin/topojson:285:25)
    at Queue._call (/home/ubuntu/workspace/node_modules/d3-queue/build/d3-queue.js:43:56)

**Comment by mbostock** [comment]
Thanks, I’ve reproduced this in 2.0, and I’m investigating now.

```
$ geo2topo -q 1e5 regions=<(shp2json -n FEMA_Regions.shp | geostitch -n) > fema.json
(node:39961) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'length' of undefined
undefined:2
{"type":"Feature","properties":{"OBJECTID":2,"REGION":"REGION IX","CNT_REGION":4,"RuleID":5,"Shape_Leng":94.2020567973,"Shape_Area":101.933956038},"geometry":{"type":"MultiPolygon","coordinates":[[[[-122.40454859271671,37.314986906636875],[-122.40455666528311,37.315097816680066],[-122.40437345312318,37.31525768859359],[-122.4042055086432,37.31528067785888],[-122.40418251937797,37.31664283569944],[-122.40414461341379,37.31701276983085],[-122.40396140125387,37.31743184132313],[-122.40390068151504,37.317973756217725],[-122.40402247197386,37.318362818821754],[-122.40409845939269,37.318942815171056],[-122.40367149082454,37.319781835608524],[-122.40342755892573,37.32057575496833],[-122.40288564403113,37.32154463843108],[-122.40325943895522,37.3214447842941],[-122.40365657412565,37.322177632933915],[-122.40362533680337,37.32278763817146],[-122.40382346566219,37.323375707087166],[-122.40386944419271,37.32375687261532],[-122.40376344788564,37.32385567380885],[-122.40373256154447,37.32400887708053],[-122.

SyntaxError: Unexpected token { in JSON at position 14255687
    at Object.parse (native)
    at ReadStream.<anonymous> (geo2topo:111:46)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by mbostock** [comment]
The failing polygon does look bad, in that it’s missing a coordinates array:

```json
{
  "type": "Feature",
  "properties": {
    "OBJECTID": 6,
    "REGION": null,
    "CNT_REGION": 1,
    "RuleID": 0,
    "Shape_Leng": 0,
    "Shape_Area": 0
  },
  "geometry": {
    "type": "Polygon"
  }
}
```

It’s possible this is a bug in [shapefile](https://github.com/mbostock/shapefile).

**Comment by mbostock** [comment]
Fixes for null geometries incoming.

```
geo2topo -n \
  regions=<( \
    shp2json -n FEMA_Regions.shp | \
    geostitch -n | \
    geoproject -n 'd3.geoAlbersUsa()') | \
  toposimplify -p 1 | \
  topo2geo regions=- | \
  geo2svg -n -p 2 > fema.svg
```

![screen shot 2016-11-01 at 2 15 30 pm](https://cloud.githubusercontent.com/assets/230541/19907813/ab83b88e-a03d-11e6-93ec-57a5bb70f5a3.png)

**Comment by eflowbeach** [comment]
Thanks - that was fast!
